services:
  - type: web
    name: discord-bot-controller
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && python src/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
